# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: Home
    url: /
  archives:
    url: /archives
  tags:
    url: /tags
  th-list:
    text: Categories
    url: /categories
  github:
    url: https://github.com/emoizhang
    target: _blank
  weibo:
    url: http://www.weibo.com/u/1934790632
    target: _blank
  link:
    text: AFAIK (Roosephu)
    url: http://roosephu.github.io
  link2:
    text: Jiaqi's Homepage
    url: http://jiaqiguan.net

# 你的头像url
avatar: /img/magician.jpeg
# avatar link
avatar_link: /about
# 头像背景图
brand: /img/yapam.jpeg
# favicon
favicon: /img/halfmoon.png
# email
email: ayllenzhang@gmail.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: Tags
archives_title: Archives
categories_title: Categories

# 文章截断
excerpt_render: false
excerpt_length: 200
excerpt_link: 阅读全文...
mathjax: true
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward: false
#  title: 谢谢大爷~
#  wechat: /img/wechat.jpg     #微信，关闭设为 false
#  alipay: /img/alipay.jpg     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
# toc: false
toc:
  list_number: true  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: false

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: c9c69dababfa1ca231e3c090e9564908

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: UA-143402466-1
google_site_verification: false

# sogou站长验证 http://zhanzhang.sogou.com/
sogou_site_verification: false

# less  
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启 disqus
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# use gitalk://github.com/gitalk/gitalk
gitalk: false
#  enable: false
#  owner: emoizhang
#  admin: emoizhang
#  repo: myblog
#  client_id: b82ece7a5d71c119b181
#  client_secret: 6b512aad62eb2ccb485f1bef45a41671d1d0d7c6
#  distractionFreeMode: false

# Valine Comment system. https://valine.js.org
valine:
  enable: true # 如果你想使用valine，请将值设置为 true
  appId: cFer952Ja6DQ1O1yE5bT2hDU-gzGzoHsz # your leancloud appId
  appKey: MzfFmkudIEwjkIT0SfkW0fCm # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: mp # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: Comments are welcome # Comment Box placeholder
  guest_info: nick,mail # Comment header info
  pageSize: 10 # comment list page size

# 是否开启Hyper Comments，填写id则启用，false则禁用。http://hypercomments.com
# Hyper Comments support. Write your id here, or false to disable
hyper_id: false


# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: true

# 版权起始年份
since_year: 2018

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: false

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter: false
#  site_uv: 站点总访客数：
#  site_pv: 站点总访问量：

# 动态定义title
title_change:
  normal: Neverland
  leave: ...Standby

# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: false

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: 京ICP备18044497号-1